### ISSUE TITLE
bug route

### ISSUE THREAD

**Issue by azkadev** [nanoexpress/nanoexpress#331]
## Bug Report
 i tried route exmaple but doesn't work
```js
var nanoexpress = require("nanoexpress"); 
var PORT = process.env.PORT || 8000 || 3000;
var app = nanoexpress();
const Route = require('nanoexpress/cjs/Route');
const route = new Route();
app.use(route);  route.get('/', async () => 'hello world');
app.listen(PORT);
```

### Minimal reproducible repo

Link here

### Current Behavior

A clear and concise description of the behavior.

### Expected behavior/code

A clear and concise description of what you expected to happen (or code).

### Environment

- Node/npm version: v19.6.1
- OS: Linux
- Addinational Info: `_type here_`

### Additional context/Screenshots

Add any other context about the problem here. If applicable, add screenshots to help explain.

### Note

- **Project is provided as-is without any support nor warranty**
- **If this issue not related to this project and exists on [core](https://github.com/uNetworking/uWebSockets.js) of this project, please close issue or not open**

**Comment by dalisoft** [comment]
@azkadev Hi and thank you for issue, can you please show additional info or write here? Just not works is not a bug, an ask for help from author developer like warranty but this project does not guarantee any warranty

**Comment by dalisoft** [comment]
Not a good describtion of issue, close

**Comment by ysidro** [comment]
this it's the error that i have on my case: 

`const route = new Route();
              ^
TypeError: Route is not a constructor
    at Object.<anonymous> (proyect_url/node-backend/src/routers/aouthRoutes.controller.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/admin/Documents/PROYECTOS-OMD/och8a/node-backend/src/app.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
Node.js v20.3.1`
