### ISSUE TITLE
[Bug] Throw in async routes doesnt work

### ISSUE THREAD

**Issue by victor-a-rigacci** [nanoexpress/nanoexpress#92]
```
 app.setErrorHandler((err: any, req: HttpRequest, res: HttpResponse): any => {
    const errMsg = globalVariables.SETTINGS.ENV === 'local' ? err.error.toString() : null;
    const errStack = globalVariables.SETTINGS.ENV === 'local' ? err.error.stack.toString() : null;
    console.error(errStack);
    res.status(500);
    res.send(
      {
        message: 'Server error',
        errMsg,
        errStack,
      },
    );
  });
`  app.post('/auth/google', async (req: any, res: any) => {
    throw new Error('Invalid google login');
  });
};`
```
```

(node:13708) UnhandledPromiseRejectionWarning: Error: Invalid google login
    at F:\Dev\Rmi\Tm86\api-backend\src\routes\logincallbacks.routes.ts:8:11
    at Generator.next (<anonymous>)
    at F:\Dev\Rmi\Tm86\api-backend\src\routes\logincallbacks.routes.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (F:\Dev\Rmi\Tm86\api-backend\src\routes\logincallbacks.routes.ts:4:12)
    at F:\Dev\Rmi\Tm86\api-backend\src\routes\logincallbacks.routes.ts:7:57
    at handler (F:\Dev\Rmi\Tm86\api-backend\node_modules\nanoexpress\build\nanoexpress.js:1971:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at F:\Dev\Rmi\Tm86\api-backend\node_modules\nanoexpress\build\nanoexpress.js:1749:20
(node:13708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

With not async methods work perfectly.

**Comment by victor-a-rigacci** [comment]
I see in anothers api fix using the middleware as an async:

```
app.use(async (req:any, res:any, next:any) => {
  try {
    await next();
  } catch (err) {
    console.log('upps, something just happened');
    res.send(err);
  }
});

```

But its not working this solution.

**Comment by dalisoft** [comment]
@victor-a-rigacci 

```js
app.use(async (req:any, res:any, next:any) => {
  try {
    await next();
  } catch (err) {
    console.log('upps, something just happened');
    res.send(err);
  }
});
```

This solution will never work as **nanoexpress** uses different technique to get good performance and not lost benefits of uWS performance.

Can you please create minimal reproducible repo for test?

**Comment by dalisoft** [comment]
@victor-a-rigacci I just checked [this](https://github.com/nanoexpress/nanoexpress/blob/master/examples/error-handler.js) example and it works, please, make sure your code has everything correct

**Comment by victor-a-rigacci** [comment]
I test with the example and only works if i not using typescript, when put the same example in a ts file still failing.
