### ISSUE TITLE
Duplicate Content-Length for CORS

### ISSUE THREAD

**Issue by literakl** [nanoexpress/nanoexpress#93]
I have written unit tests for my API and I realized that OPTIONS calls fails because Nanoexpress returns duplicated Content-Length header. I tried both Axios and GotJS clients. It seems that the exception is thrown inside NodeJS HTTP parser (I use NodeJS v12.16.2 now). I moved to backend and tested the same methods with NanoExpress and Express. Express test passes while Nanoexpress test fails.

Here is the repo to try it yourself: https://github.com/literakl/nano-options
Code:

```
const cors = require('cors');
app.options('/v1/users/:userId', cors());
app.options('/v1/polls/:pollId', cors(), () => {});
```

Exception:

```
RequestError: Parse Error: Duplicate Content-Length
GotError: Parse Error: Duplicate Content-Length
    at onError (node_modules\got\dist\source\request-as-event-emitter.js:140:29)
    at ClientRequest.<anonymous> (node_modules\got\dist\source\request-as-event-emitter.js:157:17)
    at ClientRequest.emit (events.js:322:22)
    at ClientRequest.origin.emit (node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketOnData (_http_client.js:483:9)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Socket.socketOnData (_http_client.js:476:22)
```

**Comment by dalisoft** [comment]
I don't know why it happens as CORS module is separate module (you using express cors module?). For my daily usage nanoexpress also works fine.
Please check yourself why and how it happens.

And any PR is welcome.
Thanks for bug report.

**Comment by dalisoft** [comment]
It's bug related to CORS module as writes header two times per request. In simple version there no cache for header due of performance reason, but on PRO version was realized by creating sub-module + Route instance

**Comment by dalisoft** [comment]
It's bug of `curl` or something at all. I debugger entire code, but found bug in `curl` or `uWS` itself because try `curl` request without any `cors` middleware, it anyways returns `Content-Length: 0`.
Default `Content-Length: 0` + CORS `Content-Length: 0` = Duplicate

**Comment by dalisoft** [comment]
This bug applies to all versions of `nanoexpress`

**Comment by dalisoft** [comment]
I will fix it as i can, but in near week or month i cannot

**Comment by literakl** [comment]
Thank you. And you do not need to hurry, I have a workaround.

st 22. 4. 2020 v 19:40 odesílatel dalisoft <notifications@github.com>
napsal:
